permissions:
  contents: write

on:
  workflow_dispatch:
    
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/uwx/UdonSharp
          git subtree split --prefix=Packages/com.merlin.UdonSharp -b split
          git remote add usharp https://github.com/uwx/USharpSplit
          git checkout split
          git pull usharp main
          git push usharp main
